{"level":"ERROR","location":"[delete_call:142] fyersModel","message":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /api/v3/positions (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))","timestamp":"2024-01-23 15:14:58,143+0530","service":"FyersDataSocket"}
